# Generated by Django 5.1.7 on 2025-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('gif_url', models.URLField()),
                ('youtube_link', models.URLField()),
            ],
        ),
    ]
